### ISSUE TITLE
Smashing a Toxic Waste Barrel drop 2 barrels instead of one

### ISSUE THREAD

**Issue by fluxxdog** [NeoVanAlemania/EnhancedStorage#4]
Landed on a Toxic planet, came across a Toxic Waste Barrel (id: toxicwastebarrel), and used the Matter Manipulator to break it. Instead of one barrel, it dropped 2. If I come across any others, I'll update this.

**Comment by NeoVanAlemania** [comment]
I can confirm the issue, thanks for reporting
